-- 0013 枠の行に「その月の頻度」と「その月の支払い待ち件数」を持たせる
--
--   ★なぜ要るのか（2026-10-09・段階3-b の関門①で判明）
--     顧客の画面に出す残数を、写し（member_home）ではなくD1の行から作りたい。
--     ところが写しの中身は残数だけではなく、**表示の補助**が混ざっている。
--     それがD1の3表（枠・チケット・引当）から作れない。
--
--       carryover（繰越）    quota は「頻度＋繰越」。**頻度が無いと分解できない**
--       overageCount（支払い待ち）
--                            未割当の予約は**引当の行が作られない**＝3表に現れない
--
--     ★特に支払い待ちが作れないのは重い。0として扱うと、
--       支払いが必要な方に「残り0回」だけが出て、マイナスと支払いの案内が消える
--       （オーナーの運用：未払いぶんを先に押さえ、次回のセッションで支払い→チケット付与）。
--
--   ★どちらも枠を作るときに既に手元にある
--       base_freq … buildQuotaForCustomer が res.freq を持っている
--                   （2026-10-08 に「枠を決めた行の頻度」へ揃えた）
--       overage   … buildAllocationsForCustomer が perSession を持っている
--                   未割当のうち、**入力の誤りを除いた**ものだけを数える
--                   （数え方は GAS の _lbOverageOf と同じ規則にする）
--
--   ★既定値は入れる（0012 の coverage とは違う）
--     coverage は「入っていない行」を見分ける必要があったので既定なしにした。
--     こちらは 0 が自然な初期値で、作り直せば正しい値が入る。
--     ただし**作り直す前は carryover が過大に見える**（quota − 0 = quota）。
--     だから読む側は、この列が入っているかを coverage と同じく確かめる必要がある。
--     → base_freq は NULL 許容にし、NULL のうちは「まだ作り直していない」と分かるようにする。

ALTER TABLE monthly_quota ADD COLUMN base_freq INTEGER;                    -- NULL＝まだ作り直していない
ALTER TABLE monthly_quota ADD COLUMN overage INTEGER NOT NULL DEFAULT 0;   -- その月の支払い待ち件数
